global using System;
global using System.IO;
global using System.Collections.Generic;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using Microsoft.Win32;
global using Microsoft.WindowsAPICodePack.Dialogs;
global using System.Windows.Media;
global using Effects.bin_Editor.Effects_File;
global using Color = System.Windows.Media.Color;
