global using System;
global using System.IO;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Navigation;
global using System.Windows.Shapes;
global using Microsoft.Win32;
global using Microsoft.WindowsAPICodePack.Dialogs;
global using EffectsBinEditorWPF.Effects_File;

